export interface MatnEpisode {
  episodeNum: number
  title?: string
  youtubeUrl?: string
  youtubeId?: string
  videoUrl?: string // رابط أو ملف الفيديو المرفوع من اللابتوب
  audioUrl?: string
  description?: string
  duration?: string
}

export interface MatnCourse {
  slug: string
  title: string
  author?: string // مؤلف أو ناظم المتن
  stage?: 1 | 2 | 3 // مرحلة التأصيل في خارطة الطريق: 1 تأسيس، 2 بناء، 3 تمكن
  category: string
  categorySlug: string
  instructor?: string
  youtubeId: string
  videoUrl?: string // ملف الفيديو المباشر المرفوع من اللابتوب للمتن
  isPlaylist: boolean
  description: string
  totalLessons?: number
  videoList?: string[]
  reversePlaylist?: boolean
  pdfUrl?: string
  audioUrl?: string
  summary?: string
  episodes?: MatnEpisode[] // قائمة المجالس المتفرعة بروابطها المخصصة
  prerequisites?: string[] // المتطلبات السابقة الموصى بها
  nextCourses?: string[] // المتون التالية المقترحة بعد إتمام هذا المتن
  pedagogicalRole?: string // دور المتن في البناء المعرفي للطالب
}


export const CATEGORIES_LIST = [
  { slug: 'hadith', title: 'الحديث النبوي ومصطلحه' },
  { slug: 'aqeedah', title: 'العقيدة والتأصيل الإيماني' },
  { slug: 'usul-al-fiqh', title: 'أصول الفقه' },
  { slug: 'fiqh-rules', title: 'القواعد الفقهية' },
  { slug: 'fiqh', title: 'الفقه الإسلامي' },
  { slug: 'manners', title: 'الآداب والأخلاق الإسلامية' },
  { slug: 'seerah-history', title: 'السيرة النبوية والتاريخ' },
  { slug: 'arabic-language', title: 'علوم الآلة ولسان العرب' },
  { slug: 'quran-sciences', title: 'علوم القرآن والتفسير' },
]

export const ALL_COURSES: MatnCourse[] = [
  // 1. حلية طالب العلم
  {
    slug: 'hilyat-talib-al-ilm',
    title: 'حلية طالب العلم',
    author: 'الشيخ بكر بن عبد الله أبو زيد',
    stage: 1,
    category: 'الآداب والأخلاق الإسلامية',
    categorySlug: 'manners',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzIAeEFKqjQEVV99dH4HnZ8c',
    isPlaylist: true,
    totalLessons: 14,
    description: 'آداب الطلب وسمت حامل الشريعة ومعاقد تعظيم العلم وبيان مفاتيح التحصيل والتأصيل.',
  },
  // 2. بداية المتفقه
  {
    slug: 'bidayat-al-mutafaqqih',
    title: 'بداية المتفقه',
    author: 'الشيخ وحيد بن عبد السلام بالي',
    stage: 1,
    category: 'الفقه الإسلامي',
    categorySlug: 'fiqh',
    instructor: 'الشيخ د. نور شعلان',
    youtubeId: 'PLw7kd5CfK4rbbXeTiKLJU_3qHkX0IPaZ9',
    isPlaylist: true,
    totalLessons: 52,
    description: 'متن فقهي تأسيسي يجمع أبواب العبادات والمعاملات على الدليل من الكتاب والسنة.',
  },
  // 3. الأربعين النووية 1
  {
    slug: '40-hadith-nawawi-1',
    title: 'الأربعين النووية',
    author: 'الإمام يحيى بن شرف النووي',
    stage: 1,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzIAeEFKqjQEVV99dH4HnZ8c',
    isPlaylist: true,
    totalLessons: 50,
    description: 'شرح تحليلي وتأصيلي لأحاديث الأربعين النووية مع زيادات ابن رجب وجوامع كلم النبي ﷺ.',
  },
  // 4. الأربعين النووية 2
  {
    slug: '40-hadith-nawawi-2',
    title: 'الأربعين النووية',
    author: 'الإمام يحيى بن شرف النووي',
    stage: 1,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'الشيخ د. صالح بن عبد الله العصيمي',
    youtubeId: 'guEgbipv6fY',
    isPlaylist: false,
    totalLessons: 2,
    videoList: ['guEgbipv6fY', 'rElbLaqpaDs'],
    description: 'شرح وجيز وضبط لألفاظ أحاديث الأربعين النووية في مجلسين مباركين.',
  },
  // 5. كتاب البداية في علم العقيدة
  {
    slug: 'al-bidayah-aqeedah',
    title: 'كتاب البداية في علم العقيدة',
    author: 'الشيخ وحيد بن عبد السلام بالي',
    stage: 1,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'الشيخ مصطفى زُهر',
    youtubeId: 'PLJUXZilZ8fUUIL8RfFRUv3qvebt_HOmre',
    isPlaylist: true,
    totalLessons: 20,
    description: 'مدخل تأسيسي وميسر في أركان الإيمان وأصول الاعتقاد للمبتدئين.',
  },
  // 6. كتاب صحيح الآداب الإسلامية
  {
    slug: 'sahih-al-adab',
    title: 'كتاب صحيح الآداب الإسلامية',
    author: 'الشيخ وحيد بن عبد السلام بالي',
    stage: 1,
    category: 'الآداب والأخلاق الإسلامية',
    categorySlug: 'manners',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzIsGhGLYdzsIQKD2wEJH4We',
    isPlaylist: true,
    totalLessons: 28,
    description: 'الآداب النبوية والأخلاق المحمدية في المعاشرة والتعامل وطهارة الباطن.',
  },
  // 7. كتاب التوحيد
  {
    slug: 'kitab-al-tawhid',
    title: 'كتاب التوحيد الذي هو حق الله على العبيد',
    author: 'الإمام محمد بن عبد الوهاب',
    stage: 2,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzKPNsDtNbrCIyOgyxO8kH-2',
    isPlaylist: true,
    totalLessons: 35,
    description: 'عمدة كتب التوحيد في بيان حق الله والتحذير من الشرك الأكبر والأصغر وذرائعه.',
  },
  // 8. الأصول الثلاثة
  {
    slug: 'three-principles',
    title: 'الأصول الثلاثة وأدلتها',
    author: 'الإمام محمد بن عبد الوهاب',
    stage: 1,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'الشيخ د. مطلق الجاسر',
    youtubeId: 'PLjpZThbHfMTXZBfxbXILruw_4L-nu129x',
    isPlaylist: true,
    totalLessons: 10,
    description: 'معرفة العبد ربه ودينه ونبيه محمد ﷺ بالبراهين الجلية من القرآن والسنة.',
  },
  // 9. القواعد الأربعة
  {
    slug: 'four-principles',
    title: 'القواعد الأربعة',
    author: 'الإمام محمد بن عبد الوهاب',
    stage: 1,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'الشيخ د. عثمان الخميس',
    youtubeId: 'd5Q5jK16NvA',
    isPlaylist: false,
    totalLessons: 1,
    description: 'قواعد التوحيد الفاصلة بين الموحدين والمشركين في معنى الشفاعة والعبادة.',
  },
  // 10. الأصول الستة
  {
    slug: 'six-principles',
    title: 'الأصول الستة',
    author: 'الإمام محمد بن عبد الوهاب',
    stage: 1,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'الشيخ د. عبد السلام الشويعر',
    youtubeId: 'dd27c-pxiAk',
    isPlaylist: false,
    totalLessons: 1,
    description: 'بيان الأصول العظام التي نص عليها الكتاب العزيز وأغفلها كثير من الناس.',
  },
  // 11. القواعد المثلى في أسماء الله وصفاته
  {
    slug: 'al-qawaid-al-muthla',
    title: 'القواعد المثلى في أسماء الله وصفاته',
    author: 'الشيخ محمد بن صالح العثيمين',
    stage: 2,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzL7NYFQU-TvQoa4E8B0eK9H',
    isPlaylist: true,
    totalLessons: 18,
    description: 'قواعد أهل السنة والجماعة المحكمة في إثبات أسماء الله وصفاته وتنزيهه.',
  },
  // 12. كتاب المنيرة
  {
    slug: 'al-munirah',
    title: 'كتاب المنيرة في السيرة',
    author: 'الشيخ صالح العصيمي',
    stage: 1,
    category: 'السيرة النبوية والتاريخ',
    categorySlug: 'seerah-history',
    instructor: 'الشيخ د. عامر بهجت',
    youtubeId: 'PLbvXMO-CwjdVsr_MnzTQdGf9O9-F-kHxw',
    isPlaylist: true,
    totalLessons: 10,
    description: 'منظومة المنيرة في السيرة النبوية وبيان وقائعها الكبرى بإيجاز محكم.',
  },
  // 13. الأرجوزة الميئية
  {
    slug: 'al-urjuzah-al-miiyyah',
    title: 'الأرجوزة الميئية في حال أشرف البرية',
    author: 'ابن أبي العز الحنفي',
    stage: 1,
    category: 'السيرة النبوية والتاريخ',
    categorySlug: 'seerah-history',
    instructor: 'الشيخ عبد الرزاق البدر',
    youtubeId: 'PLUtxhBXriVhPrT4GLNVmhQtgdb-QET2yg',
    isPlaylist: true,
    totalLessons: 12,
    description: 'مائة بيت لابن أبي العز الحنفي في ترتيب أحداث السيرة النبوية سنة فسنة.',
  },
  // 14. حقبة من التاريخ
  {
    slug: 'hiqbah-min-al-tareekh',
    title: 'حقبة من التاريخ',
    author: 'الشيخ د. عثمان الخميس',
    stage: 2,
    category: 'السيرة النبوية والتاريخ',
    categorySlug: 'seerah-history',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLJUXZilZ8fUV5VKByoryZM1n0eSPg4VOA',
    isPlaylist: true,
    totalLessons: 24,
    description: 'تحرير الأحداث التاريخية في عهد الخلفاء الراشدين والفتنة وموقف الصحابة.',
  },
  // 15. الشمائل المحمدية للإمام الترمذي
  {
    slug: 'al-shamail-al-mohammadiyyah',
    title: 'الشمائل المحمدية للإمام الترمذي',
    author: 'الإمام أبو عيسى الترمذي',
    stage: 1,
    category: 'السيرة النبوية والتاريخ',
    categorySlug: 'seerah-history',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzJg7jCQmCDNi0YtBS3AN1YN',
    isPlaylist: true,
    totalLessons: 22,
    description: 'أوصاف النبي ﷺ الخَلقية والخُلقية وهديه في ملبسه وطعامه ونومه وعبادته.',
  },
  // 16. شرح البداية في أصول الفقه
  {
    slug: 'al-bidayah-usul',
    title: 'شرح البداية في أصول الفقه',
    author: 'الشيخ وحيد بن عبد السلام بالي',
    stage: 1,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'الشيخ أيمن بن موسى',
    youtubeId: 'PLySepU4QsBNYaDbFcF0x8XBsooQV1sANR',
    isPlaylist: true,
    totalLessons: 15,
    description: 'مبادئ علم الأصول وقواعد الاستنباط والأدلة المتفق عليها والمختلف فيها.',
  },
  // 17. التأهيل الفقهي: أصول الفقه
  {
    slug: 'al-taheel-al-usuli',
    title: 'التأهيل الفقهي: أصول الفقه',
    author: 'كتاب التأهيل الفقهي على مذهب الإمام أحمد',
    stage: 1,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'الشيخ د. عامر بهجت',
    youtubeId: 'PLsf2FZwVKc8j2YHdgn8e_9kzs9-RqCYLb',
    isPlaylist: true,
    totalLessons: 18,
    description: 'بناء الملكة الأصولية وتدريب الطالب على استخراج دلالات الألفاظ والعلل.',
  },
  // 18. الكفاية في شرح البداية: أصول الفقه
  {
    slug: 'al-kifayah-usul',
    title: 'الكفاية في شرح البداية: أصول الفقه',
    author: 'د. خالد الجهني',
    stage: 2,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'الشيخ كمال شرف',
    youtubeId: 'PLuVDKTcJ5LzNg_jNhbNdGeni9LPaGxKGQ',
    isPlaylist: true,
    totalLessons: 20,
    description: 'شرح تحليلي وتفصيلي لقواعد علم الأصول ومسائله الكلية والفرعية.',
  },
  // 19. العقيدة الواسطية
  {
    slug: 'al-aqeedah-al-wasitiyyah',
    title: 'العقيدة الواسطية لشيخ الإسلام ابن تيمية',
    author: 'شيخ الإسلام ابن تيمية',
    stage: 2,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'الشيخ د. مطلق الجاسر',
    youtubeId: 'PLjpZThbHfMTWp5OlwZm97S-akAgXSDHoI',
    isPlaylist: true,
    totalLessons: 30,
    description: 'تقرير عقيدة الفرقة الناجية المنصورة في توحيد الأسماء والصفات والإيمان والقدر.',
  },
  // 20. البداية في علم المصطلح
  {
    slug: 'al-bidayah-mustalah',
    title: 'البداية في علم المصطلح',
    author: 'الشيخ وحيد بن عبد السلام بالي',
    stage: 1,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzJ-j6BRCzZGz4Z771hcn_DF',
    isPlaylist: true,
    totalLessons: 16,
    description: 'مدخل تأسيسي في أقسام الحديث وصفات الرواة وقواعد القبول والرد.',
  },
  // 21. البداية في علوم القرآن
  {
    slug: 'al-bidayah-ulum-quran',
    title: 'البداية في علوم القرآن',
    author: 'الشيخ وحيد بن عبد السلام بالي',
    stage: 1,
    category: 'علوم القرآن والتفسير',
    categorySlug: 'quran-sciences',
    instructor: 'الشيخ سامي بالي',
    youtubeId: 'PLySepU4QsBNZa3GhH7TB8nkn5y9tbSivL',
    isPlaylist: true,
    totalLessons: 15,
    description: 'مبادئ جمع القرآن ونزوله والمكي والمدني والناسخ والمنسوخ والإعجاز.',
  },
  // 22. القواعد الفقهية الميسرة
  {
    slug: 'al-qawaid-al-fiqhiyyah-al-muyassarah',
    title: 'القواعد الفقهية الميسرة',
    author: 'د. عبد الشكور معلم عبد فارح',
    stage: 1,
    category: 'القواعد الفقهية',
    categorySlug: 'fiqh-rules',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzLyIsQ7yQUCsgyalRRHW9y3',
    isPlaylist: true,
    totalLessons: 14,
    description: 'القواعد الفقهية الكبرى الخمس وما يتفرع عنها من ضوابط وتطبيقات معاصرة.',
  },
  // 23. منظومة القواعد الفقهية
  {
    slug: 'manzumat-al-qawaid-al-fiqhiyyah',
    title: 'منظومة القواعد الفقهية للعلامة السعدي',
    author: 'الشيخ عبد الرحمن بن ناصر السعدي',
    stage: 1,
    category: 'القواعد الفقهية',
    categorySlug: 'fiqh-rules',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzJGlrZ1o5qWmY3xYARv9iqB',
    isPlaylist: true,
    totalLessons: 12,
    description: 'شرح المنظومة الرائعة في ضبط أصول الفقه وقواعد الشريعة الجامعة.',
  },
  // 24. خلاصة تعظيم العلم
  {
    slug: 'tazeem-al-ilm',
    title: 'خلاصة تعظيم العلم ومفاتح الطلب',
    author: 'الشيخ صالح بن عبد الله العصيمي',
    stage: 1,
    category: 'الآداب والأخلاق الإسلامية',
    categorySlug: 'manners',
    instructor: 'د. عثمان الخميس',
    youtubeId: 'PLx3Fh1kiMbrepiLh7zeqoIAqUC2Epazdz',
    isPlaylist: true,
    totalLessons: 15,
    description: 'معاقد تعظيم العلم وبيان معالم التحصيل والتأصيل وطرد الفتور والملل.',
  },
  // 25. أدلة بداية المتفقه
  {
    slug: 'adillat-bidayat-al-mutafaqqih',
    title: 'أدلة بداية المتفقه',
    author: 'الشيخ أيمن بن علي موسى',
    stage: 2,
    category: 'الفقه الإسلامي',
    categorySlug: 'fiqh',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzJS_HbbK7ccRFMAUyAXz1Yk',
    isPlaylist: true,
    totalLessons: 40,
    description: 'تخريج واستدلال المسائل الفقهية وبيان وجوه الدلالة من نصوص الوحيين.',
  },
  // 26. مختصر السيرة (د. مطلق الجاسر)
  {
    slug: 'mukhtasar-al-seerah-jaser',
    title: 'مختصر السيرة النبوية',
    author: 'الإمام عبد الغني المقدسي',
    stage: 1,
    category: 'السيرة النبوية والتاريخ',
    categorySlug: 'seerah-history',
    instructor: 'د. مطلق الجاسر',
    youtubeId: 'PLTvV1vg05rlDkxu8QlsF4FaYsYLODHg2S',
    isPlaylist: true,
    totalLessons: 16,
    description: 'محطات مضيئة وتأصيل رصين في سيرة سيد المرسلين عليه الصلاة والسلام.',
  },
  // 27. دورة شرح النحو الصغير (د. سليمان العيوني)
  {
    slug: 'al-nahw-al-saghir',
    title: 'دورة شرح النحو الصغير',
    author: 'د. سليمان بن عبد العزيز العيوني',
    stage: 1,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. سليمان العيوني',
    youtubeId: 'PLz4yyONLBRGDlM28-40mRwt-jimRUmAY7',
    isPlaylist: true,
    totalLessons: 20,
    description: 'ضبط قواعد النحو الأساسية والتدريب على الإعراب بأسلوب علمي ممتع.',
  },
  // 28. شرح متن الأجرومية (د. سليمان العيوني)
  {
    slug: 'al-ajrumiyyah',
    title: 'الدروس التأصيلية: شرح متن الآجرومية',
    author: 'ابن آجروم الصنهاجي',
    stage: 1,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. سليمان العيوني',
    youtubeId: 'PL54tsaxKeZjP3ZXGyP3HpgPY3b4SqNrI_',
    isPlaylist: true,
    totalLessons: 25,
    description: 'العمدة الأولى في النحو والإعراب وبيان أقسام الكلم وعلامات الإعراب.',
  },
  // 29. البداية في الصرف (الشيخ أحمد نبيل)
  {
    slug: 'al-bidayah-fi-al-sarf',
    title: 'البداية في علم الصرف',
    author: 'الشيخ وحيد بن عبد السلام بالي',
    stage: 1,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLJUXZilZ8fUWwS4GwQb9GbE1ZkNiHAosP',
    isPlaylist: true,
    totalLessons: 18,
    description: 'ضبط بنية الكلمة العربية وأوزان الأفعال والأسماء والمصادر والمشتقات.',
  },
  // 30. البداية في البلاغة (الشيخ أحمد نبيل)
  {
    slug: 'al-bidayah-fi-al-balaghah',
    title: 'البداية في علم البلاغة',
    author: 'الشيخ وحيد بن عبد السلام بالي',
    stage: 1,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLJUXZilZ8fUURz3RnvOJsPoY9mJghSZHJ',
    isPlaylist: true,
    totalLessons: 16,
    description: 'علوم المعاني والبيان والبديع للمبتدئين لتدبر كتاب الله وفهم أسرار العربية.',
  },
  // 31. نخبة الفكر (د. عبد العزيز الشايع)
  {
    slug: 'nukhbat-al-fikar',
    title: 'نخبة الفكر في مصطلح أهل الأثر',
    author: 'الحافظ ابن حجر العسقلاني',
    stage: 2,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'د. عبد العزيز الشايع',
    youtubeId: 'PL9LhdwtGvkd9ZRR9mDLrsHbxkcHgAQ6MD',
    isPlaylist: true,
    totalLessons: 18,
    description: 'متن الحافظ ابن حجر المحرر العمدة في مصطلح الحديث وقواعد التصحيح والتضعيف.',
  },
  // 32. قصب السكر في منظومة نخبة الفكر (د. عبد السلام الشويعر)
  {
    slug: 'qasab-al-sukkar',
    title: 'قصب السكر في منظومة نخبة الفكر',
    author: 'محمد بن إسماعيل الصنعاني',
    stage: 2,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'د. عبد السلام الشويعر',
    youtubeId: 'PL54tsaxKeZjM2RJu2MZ0XXKxWgi_pA80T',
    isPlaylist: true,
    totalLessons: 15,
    description: 'شرح منظومة الصنعاني في نظم نخبة الفكر وبيان دقائقها ومصطلحاتها.',
  },
  // 33. جوامع الأخبار للسعدي (الشيخ عبد الكريم الخضير)
  {
    slug: 'jawami-al-akhbar',
    title: 'شرح جوامع الأخبار للسعدي',
    author: 'الشيخ عبد الرحمن بن ناصر السعدي',
    stage: 1,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'الشيخ عبد الكريم الخضير',
    youtubeId: 'PL6C71skKjoGsyFKadLlPjfAI_j9RxXq8B',
    isPlaylist: true,
    totalLessons: 20,
    description: 'أحاديث نبوية جامعة في الفقه والآداب والأخلاق ومقاصد الشريعة.',
  },
  // 34. جوامع الأخبار للسعدي ترجمة إنجليزية (عثمان الخميس)
  {
    slug: 'jawami-al-akhbar-en',
    title: 'جوامع الأخبار (ترجمة وبيان إنجليزي)',
    author: 'الشيخ عبد الرحمن بن ناصر السعدي',
    stage: 1,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'د. عثمان الخميس',
    youtubeId: 'PLx3Fh1kiMbrf0uTqUHb4d91JnCi4eWlJH',
    isPlaylist: true,
    totalLessons: 12,
    description: 'مدارسة جوامع الأخبار مع تقريب معانيها وتدريب الطالب على دعوة غير العرب.',
  },
  // 35. درة البيان في أصول الإيمان
  {
    slug: 'durrat-al-bayan',
    title: 'درة البيان في أصول الإيمان',
    author: 'د. محمد يسري إبراهيم',
    stage: 1,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'د. محمد يسري إبراهيم',
    youtubeId: 'PLnyZ09UdyUW5oANhA5CEzAXJbfW439Nq-',
    isPlaylist: true,
    totalLessons: 16,
    description: 'خلاصة محررة لأصول العقيدة السلفية بالدليل من الكتاب والسنة وإجماع السلف.',
  },
  // 36. شرح كتاب منهاج السالكين
  {
    slug: 'minhaj-al-salikeen',
    title: 'شرح كتاب منهاج السالكين وتوضيح الفقه في الدين',
    author: 'الشيخ عبد الرحمن بن ناصر السعدي',
    stage: 2,
    category: 'الفقه الإسلامي',
    categorySlug: 'fiqh',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzL7HS1wVLzPkkeQ1NrXoO39',
    isPlaylist: true,
    totalLessons: 45,
    description: 'فقه ميسر مقرون بالدليل بعيد عن التعقيد يغطي سائر أبواب الشريعة.',
  },
  // 37. الخلاصة في القواعد الفقهية
  {
    slug: 'al-khulasah-fi-al-qawaid',
    title: 'الخلاصة في القواعد الفقهية',
    author: 'د. خالد بن علي المشيقح',
    stage: 1,
    category: 'القواعد الفقهية',
    categorySlug: 'fiqh-rules',
    instructor: 'د. خالد بن علي المشيقح',
    youtubeId: 'PL3vRQE1KKNIHS2ZkUtgW6cbJBL-QIqTDy',
    isPlaylist: true,
    totalLessons: 14,
    description: 'تقريب القواعد الفقهية وصياغتها وتطبيقها على النوازل والمعاملات الحديثة.',
  },
  // 38. برنامج غريب القرآن
  {
    slug: 'gharib-al-quran',
    title: 'برنامج غريب القرآن',
    author: 'الإمام ابن قتيبة الدينوري',
    stage: 2,
    category: 'علوم القرآن والتفسير',
    categorySlug: 'quran-sciences',
    instructor: 'الشيخ عبد الرحمن بن معاضة الشهري',
    youtubeId: 'PLoslTfCHb8N9D8iXwxV88DCY3Fic7kd97',
    isPlaylist: true,
    totalLessons: 30,
    description: 'بيان المفردات القرآنية التي تحتاج إلى إيضاح وبيان في لسان العرب.',
  },
  // 39. برنامج غريب الحديث
  {
    slug: 'gharib-al-hadith',
    title: 'برنامج غريب الحديث',
    author: 'أبو عبيد القاسم بن سلام / ابن قتيبة',
    stage: 2,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'الشيخ محمد العتيبي',
    youtubeId: 'PL9LhdwtGvkd8ABmn_zgqkyRSzIhc2mVUu',
    isPlaylist: true,
    totalLessons: 25,
    description: 'كشف الألفاظ النبوية الغامضة وبيان دلالاتها اللغوية والشرعية.',
  },
  // 40. شرح الأصول من علم الأصول
  {
    slug: 'al-usul-min-ilmil-usul',
    title: 'شرح الأصول من علم الأصول',
    author: 'الشيخ محمد بن صالح العثيمين',
    stage: 2,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'د. محمد باجابر',
    youtubeId: 'PLwlXp17rLNq8u9IDTz1FQLompXu_wPffu',
    isPlaylist: true,
    totalLessons: 24,
    description: 'متن ابن عثيمين المحرر في مباحث الأدلة والأحكام ودلالات الألفاظ والاجتهاد.',
  },
  // 41. شرح فروع الفقه
  {
    slug: 'furu-al-fiqh',
    title: 'شرح فروع الفقه والمسائل التطبيقية',
    author: 'ابن المبرد الحنبلي',
    stage: 2,
    category: 'الفقه الإسلامي',
    categorySlug: 'fiqh',
    instructor: 'د. عبد السلام الشويعر',
    youtubeId: 'PLl9thoP_s9vXZouL53qcSFWbF6n5TPSOV',
    isPlaylist: true,
    totalLessons: 30,
    description: 'دراسة وتدريب على المسائل الفرعية وتخريجها على القواعد والأصول.',
  },
  // 42. شرح عمدة الأحكام في أحاديث الأحكام
  {
    slug: 'umdat-al-ahkam',
    title: 'شرح عمدة الأحكام في أحاديث الأحكام',
    author: 'الإمام عبد الغني المقدسي',
    stage: 2,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'د. محمد باجابر',
    youtubeId: 'PLwlXp17rLNq8omeAYSJg3lgwmy7d7WRgf',
    isPlaylist: true,
    totalLessons: 42,
    description: 'الأحاديث الفقهية المتفق عليها في صحيحي البخاري ومسلم في العبادات والمعاملات.',
  },
  // 43. شرح بلوغ المرام
  {
    slug: 'bulugh-al-maram',
    title: 'شرح بلوغ المرام من أدلة الأحكام',
    author: 'الحافظ ابن حجر العسقلاني',
    stage: 3,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'د. عبد السلام الشويعر',
    youtubeId: 'PL914QhoC1BhuoFVC2GdLz5hO-Vf8qP7Ba',
    isPlaylist: true,
    totalLessons: 60,
    description: 'جامع أدلة الأحكام للحافظ ابن حجر وبيان درجات الأحاديث وفقهها المستنبط.',
  },
  // 44. كتاب في مباحث علوم القرآن
  {
    slug: 'mabahith-ulum-al-quran',
    title: 'كتاب في مباحث علوم القرآن',
    author: 'الشيخ مناع القطان',
    stage: 2,
    category: 'علوم القرآن والتفسير',
    categorySlug: 'quran-sciences',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzL4hSOSzdMLlnATcQpru_e1',
    isPlaylist: true,
    totalLessons: 26,
    description: 'تأصيل وتفصيل مباحث الوحي والقراءات وضوابط التفسير ورسم المصحف.',
  },
  // 45. منظومة الزمزمي في علوم القرآن
  {
    slug: 'manzumat-al-zamzami',
    title: 'منظومة الزمزمي في علوم القرآن',
    author: 'عبد العزيز الزمزمي',
    stage: 2,
    category: 'علوم القرآن والتفسير',
    categorySlug: 'quran-sciences',
    instructor: 'الشيخ عبد الكريم الخضير',
    youtubeId: 'PLXQbyHRXkWsAvqbnCot1NxshvVlR4lfRT',
    isPlaylist: true,
    totalLessons: 14,
    description: 'نظم عبد العزيز الزمزمي في أصول التفسير وعلوم التنزيل وقواعد الفهم.',
  },
  // 46. منظومة سلم الوصول إلى علم الأصول
  {
    slug: 'sullam-al-wusul',
    title: 'منظومة سلم الوصول إلى علم الأصول',
    author: 'الشيخ حافظ الحكمي',
    stage: 2,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'د. مطلق الجاسر',
    youtubeId: 'PLjpZThbHfMTV8pRwv61RH5OxBobGzfi8i',
    isPlaylist: true,
    totalLessons: 18,
    description: 'نظم بديع في جمع قواعد ومسائل الأصوليين وترتيب الاستدلال.',
  },
  // 47. الرسالة اللطيفة في أصول الفقه المهمة
  {
    slug: 'al-risalah-al-latifah',
    title: 'الرسالة اللطيفة في أصول الفقه المهمة',
    author: 'الشيخ عبد الرحمن بن ناصر السعدي',
    stage: 1,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'د. مطلق الجاسر',
    youtubeId: 'PLjpZThbHfMTUkhZYhsmKLAeOEoXifhS4S',
    isPlaylist: true,
    totalLessons: 10,
    description: 'تأصيل مختصر نافع في مدارك الأحكام الشرعية وقواعد الاستنباط.',
  },
  // 48. صفوة أصول الفقه للسعدي
  {
    slug: 'safwat-usul-al-fiqh',
    title: 'صفوة أصول الفقه للعلامة السعدي',
    author: 'الشيخ عبد الرحمن بن ناصر السعدي',
    stage: 2,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'د. مطلق الجاسر',
    youtubeId: 'PLjpZThbHfMTXI0avAH25Lbgz_DolQnt6f',
    isPlaylist: true,
    totalLessons: 16,
    description: 'تحرير موجز ودقيق لقواعد الأصول ومسالك الاستدلال وفقه الخلاف.',
  },
  // 49. الحلل البهية على المنظومة الفقهية
  {
    slug: 'al-hulal-al-bahiyyah',
    title: 'الحلل البهية على المنظومة الفقهية',
    author: 'الشيخ عبد الرحمن بن ناصر السعدي',
    stage: 2,
    category: 'القواعد الفقهية',
    categorySlug: 'fiqh-rules',
    instructor: 'د. مطلق الجاسر',
    youtubeId: 'PLjpZThbHfMTX37Ue62QEVzQaImkCFWvd3',
    isPlaylist: true,
    totalLessons: 12,
    description: 'إيضاح بديع لأبيات القواعد الكبرى والضوابط الفقهية وتطبيقاتها.',
  },
  // 50. المنظومة الحائية
  {
    slug: 'al-haaiyyah',
    title: 'المنظومة الحائية في عقيدة أهل السنة',
    author: 'ابن أبي داود السجستاني',
    stage: 1,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'الشيخ عبد الكريم الخضير',
    youtubeId: 'PLUtxhBXriVhNCoYuzyfWB-JGAZUxtbG_y',
    isPlaylist: true,
    totalLessons: 8,
    description: 'حائية ابن أبي داود في ترسيخ عقيدة السلف الصالح وسلامة الصدر والمنهج.',
  },
  // 51. بداية العابد وكفاية الزاهد
  {
    slug: 'bidayat-al-abid',
    title: 'بداية العابد وكفاية الزاهد',
    author: 'الشيخ عبد الرحمن البعلي',
    stage: 2,
    category: 'الفقه الإسلامي',
    categorySlug: 'fiqh',
    instructor: 'د. مطلق الجاسر',
    youtubeId: 'PLjpZThbHfMTVoa9FAa4TBdHQxJMhRAl3p',
    isPlaylist: true,
    totalLessons: 24,
    description: 'متن حنبلي مختصر يقتصر على أهم المسائل الفقهية التي لا يستغني عنها مسلم.',
  },
  // 52. المختصر في العقيدة
  {
    slug: 'al-mukhtasar-aqeedah',
    title: 'شرح كتاب الخلاصة في العقيدة',
    author: 'د. خالد بن علي المشيقح',
    stage: 1,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'د. خالد بن علي المشيقح',
    youtubeId: 'PL3vRQE1KKNIHdWB4p9UGWPVF84TmorFtS',
    isPlaylist: true,
    totalLessons: 12,
    description: 'تقرير مسائل التوحيد والإيمان بعبارة عذبة وأدلة ساطعة تناسب المبتدئ.',
  },
  // 53. منظومة أصول الفقه لابن عثيمين
  {
    slug: 'manzumat-usul-uthaymeen',
    title: 'منظومة أصول الفقه لابن عثيمين',
    author: 'الشيخ محمد بن صالح العثيمين',
    stage: 2,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'د. خالد بن علي المشيقح',
    youtubeId: 'PL3vRQE1KKNIEs_mVAAMjE8BQxN7MVqsAW',
    isPlaylist: true,
    totalLessons: 14,
    description: 'نظم بديع سلس صاغه الشيخ ابن عثيمين لتقريب مباحث الأصول وحفظها.',
  },
  // 54. دورة الطريق إلى علم أصول الفقه
  {
    slug: 'al-tareeq-ila-usul-al-fiqh',
    title: 'دورة الطريق إلى علم أصول الفقه',
    author: 'د. عامر بهجت',
    stage: 1,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'د. عامر بهجت',
    youtubeId: 'PL0-ZBZXy0yoOQ4vY3HhUjjchFVXtOnjFj',
    isPlaylist: true,
    totalLessons: 16,
    description: 'منهجية شاملة وخارطة طريق لدراسة أصول الفقه والتدرج فيه حتى الرسوخ.',
  },
  // 55. تمارين أصول الفقه
  {
    slug: 'tamareen-usul-al-fiqh',
    title: 'تمارين أصول الفقه والتدريب العملي',
    author: 'د. عامر بهجت',
    stage: 1,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'د. عامر بهجت',
    youtubeId: 'PLlZrJq88MKZOrLP02jnxpxEd6UXRSvUdT',
    isPlaylist: true,
    totalLessons: 15,
    description: 'تطبيقات عملية وأسئلة تأصيلية لترسيخ القواعد الأصولية في ذهن الطالب.',
  },
  // 56. رفع الملام عن الأئمة الأعلام
  {
    slug: 'raf-al-malam',
    title: 'رفع الملام عن الأئمة الأعلام',
    author: 'شيخ الإسلام ابن تيمية',
    stage: 3,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'د. عبد السلام الشويعر والشيخ سليمان الرحيلي',
    youtubeId: 'PLlX1sKIV4qu8Q3G2J2BGDK--6ue6WxpE0',
    isPlaylist: true,
    totalLessons: 14,
    description: 'كتاب شيخ الإسلام ابن تيمية في بيان أسباب اختلاف العلماء وأعذارهم.',
  },
  // 57. الكليات الفقهية للشيخ وليد السعيدان
  {
    slug: 'al-kulliyyat-al-fiqhiyyah',
    title: 'الكليات الفقهية والضوابط الكبرى',
    author: 'الشيخ وليد بن راشد السعيدان',
    stage: 2,
    category: 'القواعد الفقهية',
    categorySlug: 'fiqh-rules',
    instructor: 'الشيخ وليد السعيدان',
    youtubeId: 'PLWywt1VgUZE2vB_nrtRplFXc6XKP59B9B',
    isPlaylist: true,
    totalLessons: 20,
    description: 'ضبط المسائل المتفرقة تحت كليات فقهية مطردة تجمع شتات الأبواب.',
  },
  // 58. العقيدة الطحاوية
  {
    slug: 'al-aqeedah-al-tahawiyyah',
    title: 'متن العقيدة الطحاوية',
    author: 'الإمام أبو جعفر الطحاوي',
    stage: 3,
    category: 'العقيدة والتأصيل الإيماني',
    categorySlug: 'aqeedah',
    instructor: 'أ.د. صالح سندي',
    youtubeId: 'PLVw9FtCy781ZSgNnw5hJm1QkniE2k6Jx8',
    isPlaylist: true,
    totalLessons: 32,
    description: 'بيان عقيدة أهل السنة والجماعة على مذهب فقهاء الملة وأئمة الحديث.',
  },
  // 59. شرح تهذيب السيرة النبوية
  {
    slug: 'tahdheeb-al-seerah',
    title: 'شرح تهذيب السيرة النبوية',
    author: 'الإمام يحيى بن شرف النووي',
    stage: 2,
    category: 'السيرة النبوية والتاريخ',
    categorySlug: 'seerah-history',
    instructor: 'أ.د. حسن بن عبد الحميد بخاري',
    youtubeId: 'PLHrRbdXRN504C9Dqn_wVRXghfJJM-8gYs',
    isPlaylist: true,
    totalLessons: 20,
    description: 'تهذيب سيرة خير البرية بأسلوب رائق وفوائد إيمانية وتربوية.',
  },
  // 60. أسباب نزول القرآن
  {
    slug: 'asbab-al-nuzul',
    title: 'الصحيح المسند من أسباب النزول',
    author: 'الشيخ مقبل بن هادي الوادعي',
    stage: 2,
    category: 'علوم القرآن والتفسير',
    categorySlug: 'quran-sciences',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzJj2YJOmoeckk4cbPZdBxpn',
    isPlaylist: true,
    totalLessons: 25,
    description: 'معرفة أسباب النزول وأثرها في فهم المعنى وتفسير الآيات بدقة.',
  },
  // 61. تفسير المشكل من غريب القرآن
  {
    slug: 'tafseer-al-mushkil',
    title: 'تفسير المشكل من غريب القرآن',
    author: 'مكي بن أبي طالب القيسي',
    stage: 2,
    category: 'علوم القرآن والتفسير',
    categorySlug: 'quran-sciences',
    instructor: 'الشيخ شعبان العودة',
    youtubeId: 'PLzgycZElueFgtZLxk0Ucxm__y0Cx86CVV',
    isPlaylist: true,
    totalLessons: 24,
    description: 'حل المشكلات اللغوية والبيانية التي استشكلها بعض المفسرين بإتقان.',
  },
  // 62. ملحة الإعراب للدكتور سليمان العيوني
  {
    slug: 'mulhat-al-irab',
    title: 'شرح ملحة الإعراب للحريري',
    author: 'القاسم بن علي الحريري',
    stage: 2,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. سليمان العيوني',
    youtubeId: 'PL9L8VhHFw1YDsWOShxy-v8Q8aAsqs8Aou',
    isPlaylist: true,
    totalLessons: 30,
    description: 'أرجوزة الحريري في النحو وقواعد الإعراب بشرح عذب وتحرير دقيق.',
  },
  // 63. المجالس النحوية للدكتور عبده الراجحي
  {
    slug: 'al-majalis-al-nahwiyyah',
    title: 'المجالس النحوية والتطبيقية',
    author: 'د. عبده الراجحي',
    stage: 2,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. عبده الراجحي',
    youtubeId: 'PLD8HFd-tSsW_N7vC8xdFvbWkhw_bawJrG',
    isPlaylist: true,
    totalLessons: 26,
    description: 'مجالس علمية تطبيقية ترتقي بالطالب من مجرد حفظ القواعد إلى تذوقها واستعمالها.',
  },
  // 64. شرح المقدمة الأزهرية (د. سليمان العيوني)
  {
    slug: 'al-muqaddimah-al-azhariyyah',
    title: 'شرح المقدمة الأزهرية في علم العربية',
    author: 'الشيخ خالد الأزهري',
    stage: 2,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. سليمان العيوني',
    youtubeId: 'PL914QhoC1BhvS6BpdnqutyYicSqh4b5u1',
    isPlaylist: true,
    totalLessons: 22,
    description: 'متن ابن آجروم وتتماته في الأزهرية لضبط أصول النحو والصرف والإملاء.',
  },
  // 65. النحو الميسر (د. محمد حسن عثمان)
  {
    slug: 'al-nahw-al-muyassar',
    title: 'النحو الميسر للمبتدئين',
    author: 'د. محمد حسن عثمان',
    stage: 1,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. محمد حسن عثمان',
    youtubeId: 'PLAS4BS2Mc3oCeFyYOjWbJWtt32mVxcIos',
    isPlaylist: true,
    totalLessons: 20,
    description: 'تقريب علم النحو للمبتدئين بالأمثلة والخرائط الذهنية المبسطة.',
  },
  // 66. شذا العرف في فن الصرف (د. محمد حسن)
  {
    slug: 'shadha-al-arf',
    title: 'شذا العرف في فن الصرف',
    author: 'الشيخ أحمد الحملاوي',
    stage: 2,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. محمد حسن عثمان',
    youtubeId: 'PLWm4dKqqpJBy-caLwkgwBbP4l_vzot3Ql',
    isPlaylist: true,
    totalLessons: 25,
    description: 'كتاب أحمد الحملاوي المحرر في علم الصرف وأبنية الأفعال والأسماء والإعلال.',
  },
  // 67. شذور الذهب (د. محمد حسن)
  {
    slug: 'shudhur-al-dhahab',
    title: 'شرح شذور الذهب في معرفة كلام العرب',
    author: 'ابن هشام الأنصاري',
    stage: 3,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. محمد حسن عثمان',
    youtubeId: 'PLWm4dKqqpJByu3kIqv3Q-gsNuwG2YD7kz',
    isPlaylist: true,
    totalLessons: 35,
    description: 'متن ابن هشام الأنصاري المتقدم في دقائق النحو وشواهده القرآنية والشعرية.',
  },
  // 68. قطر الندى (د. محمد حسن)
  {
    slug: 'qatr-al-nada',
    title: 'شرح قطر الندى وبل الصدى',
    author: 'ابن هشام الأنصاري',
    stage: 2,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. محمد حسن عثمان',
    youtubeId: 'PLGrJQVLFsooDzMvhsoTMoIsSDcX0uNfcV',
    isPlaylist: true,
    totalLessons: 30,
    description: 'المتن المتوسط الشهير لابن هشام في تقعيد النحو ومناقشة الشواهد الإعرابية.',
  },
  // 69. الكافي في قواعد الإملاء (الشيخ أحمد نبيل)
  {
    slug: 'al-kafi-fi-al-imla',
    title: 'شرح كتاب الوسيط في النحو (كاملة الكواري)',
    author: 'د. كاملة الكواري',
    stage: 2,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'د. محمد حسن عثمان',
    youtubeId: 'PL-heb3rHQ_VBISjDzzMlvD7XHvgaiBkBS',
    isPlaylist: true,
    totalLessons: 12,
    description: 'ضبط قواعد رسم الهمزات والألف اللينة وعلامات الترقيم وتصحيح الأخطاء الشائعة.',
  },
  // 70. شرح البيقونية (الشيخ عبد الكريم الخضير)
  {
    slug: 'sharh-al-bayquniyyah',
    title: 'شرح المنظومة البيقونية في مصطلح الحديث',
    author: 'عمر بن محمد البيقوني',
    stage: 1,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'الشيخ عبد الكريم الخضير',
    youtubeId: 'PLUtxhBXriVhPz5N09g6zFgiumIpCIBjW7',
    isPlaylist: true,
    totalLessons: 14,
    description: 'أشهر المنظومات التأسيسية في مصطلح الحديث وأنواع الأحاديث وتعريفاتها.',
  },
  // 71. التذكرة في مصطلح الحديث (د. مطلق الجاسر)
  {
    slug: 'al-tadhkirah-mustalah',
    title: 'التذكرة في مصطلح الحديث لابن الملقن',
    author: 'ابن الملقن السراج الشافعي',
    stage: 1,
    category: 'الحديث النبوي ومصطلحه',
    categorySlug: 'hadith',
    instructor: 'د. مطلق الجاسر',
    youtubeId: 'PLjpZThbHfMTU5Z9WGeZkqMcjHto2ncVFQ',
    isPlaylist: true,
    totalLessons: 12,
    description: 'متن ابن الملقن اللطيف في تلخيص أنواع الحديث وقواعد الرواية والدراية.',
  },
  // 72. شرح كتاب الإعلام في أصول الفقه (الشيخ عبد الفتاح مصيلحي)
  {
    slug: 'kitab-al-ilam-usul',
    title: 'شرح كتاب الإعلام في أصول الفقه',
    author: 'الشيخ عبد الفتاح مصيلحي',
    stage: 2,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'الشيخ عبد الفتاح مصيلحي',
    youtubeId: 'PLCcOLqCbYTcuhrLbU0JRDspQNVsVeqqXI',
    isPlaylist: true,
    totalLessons: 20,
    description: 'تأصيل وتفصيل في مسائل أصول الفقه ومباحث الأدلة وطرق الاستنباط.',
  },
  // 73. شرح كتاب الرسالة للإمام الشافعي (الشيخ أحمد نبيل)
  {
    slug: 'kitab-al-risalah-nabil',
    title: 'شرح كتاب الرسالة للإمام الشافعي (الشيخ أحمد نبيل)',
    author: 'الإمام محمد بن إدريس الشافعي',
    stage: 3,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzIGx3Suu7ZtuWweAN9GpH-b',
    isPlaylist: true,
    totalLessons: 30,
    description: 'قراءة وتحليل لكتاب الرسالة؛ أول كتاب أُفرد في تأصيل أصول الفقه والبيان.',
  },
  // 74. شرح كتاب الرسالة للإمام الشافعي (الشيخ عبد الفتاح مصيلحي)
  {
    slug: 'kitab-al-risalah-moseilhi',
    title: 'شرح كتاب الرسالة للإمام الشافعي (الشيخ عبد الفتاح مصيلحي)',
    author: 'الإمام محمد بن إدريس الشافعي',
    stage: 3,
    category: 'أصول الفقه',
    categorySlug: 'usul-al-fiqh',
    instructor: 'الشيخ عبد الفتاح مصيلحي',
    youtubeId: 'PLmtrnJEvpXWW5spKFsxV0nVE5b4UIxhKw',
    isPlaylist: true,
    totalLessons: 32,
    description: 'مدارسة فقهية أصولية معمقة لنصوص كتاب الرسالة وقواعد الإمام الشافعي.',
  },
  // 75. شرح موسوعة مسائل الجمهور (الشيخ أحمد نبيل)
  {
    slug: 'masail-al-jumhoor',
    title: 'شرح موسوعة مسائل الجمهور في الفقه الإسلامي',
    author: 'الشيخ أحمد نبيل',
    stage: 3,
    category: 'الفقه الإسلامي',
    categorySlug: 'fiqh',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLW_RdzE7AQzJf3X4gF8cOxjXog-a5iYFS',
    isPlaylist: true,
    totalLessons: 40,
    description: 'جمع وضبط المسائل الفقهية التي اتفقت عليها جماهير أهل العلم من الأئمة الأربعة.',
  },
  // 76. شرح كتاب النحو الكافي (الشيخ أحمد نبيل)
  {
    slug: 'al-nahw-al-kafi',
    title: 'شرح كتاب النحو الكافي',
    author: 'الشيخ أيمن أمين عبد الغني',
    stage: 2,
    category: 'علوم الآلة ولسان العرب',
    categorySlug: 'arabic-language',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLJUXZilZ8fUWL6Qr_q2gAZf5hrmDbvzpI',
    isPlaylist: true,
    totalLessons: 28,
    description: 'كتاب جامع في النحو العربي وتطبيقاته وقواعد الإعراب بأسلوب منهجي سلس.',
  },
  // 77. شرح كتاب الإجماع لابن المنذر (الشيخ أحمد نبيل)
  {
    slug: 'kitab-al-ijma-nabil',
    title: 'شرح كتاب الإجماع لابن المنذر (الشيخ أحمد نبيل)',
    author: 'الإمام ابن المنذر النيسابوري',
    stage: 3,
    category: 'الفقه الإسلامي',
    categorySlug: 'fiqh',
    instructor: 'الشيخ أحمد نبيل',
    youtubeId: 'PLJUXZilZ8fUW08SwJ0On2genMcrKhxgKU',
    isPlaylist: true,
    totalLessons: 25,
    description: 'مدارسة مسائل الإجماع المنعقدة في العبادات والمعاملات مع الاستدلال والتحرير.',
  },
  // 78. شرح كتاب الإجماع لابن المنذر (الشيخ عماد الحنبلي)
  {
    slug: 'kitab-al-ijma-hanbali',
    title: 'شرح كتاب الإجماع لابن المنذر (الشيخ عماد الحنبلي)',
    author: 'الإمام ابن المنذر النيسابوري',
    stage: 3,
    category: 'الفقه الإسلامي',
    categorySlug: 'fiqh',
    instructor: 'الشيخ عماد الحنبلي',
    youtubeId: 'PLVnef98SNK6rHe4CIgbRY0Sz8gUoqb-Tc',
    isPlaylist: true,
    totalLessons: 26,
    description: 'شرح تحليلي فقهي لمسائل كتاب الإجماع على المعتمد من أقوال أئمة الحديث والفقه.',
  },
]